### ISSUE TITLE
Initialize The Blog Project

### ISSUE THREAD

**Issue by glarerena** [glarerena/blog_project#1]
# Initialize the Blog Project

### Tasks:
- [ ] Set up the project structure.
- [ ] Install required dependencies (Express, MongoDB, EJS or React).
- [ ] Create basic files (`app.js`, `index.html`, etc.).
- [ ] Set up a local development environment.

### Related Links:
- [Node.js documentation](https://nodejs.org/en/docs/)

### Milestone:
- Blog Website Setup
