### ISSUE TITLE
Create Blog Post CRUD Functionality

### ISSUE THREAD

**Issue by glarerena** [glarerena/blog_project#3]
# Create Blog Post CRUD Functionality

### Tasks:
- [ ] Create routes to create new blog posts.
- [ ] Add ability to read existing blog posts.
- [ ] Add functionality to update and delete posts.
- [ ] Connect with MongoDB for data storage.

### Milestone:
- Blog Functionality
